### PR TITLE
Pim 133 displaying timezone for datetime attr

### PR DESCRIPTION
**Pull request by Trimikraj**

### CODE REVIEW

**Review by tarjneegandhi — APPROVED** [review]
LGTM

**Review by Expressionless — CHANGES_REQUESTED** [review]
I don't see anything wrong with this, but the sendMessage method itself is 200 lines long. If this could be broken down into multiple methods this would be great, as it would make for more cohesive code

**Comment by varunshastry** [comment]
> I don't see anything wrong with this, but the sendMessage method itself is 200 lines long. If this could be broken down into multiple methods this would be great, as it would make for more cohesive code

**Comment by varunshastry** [comment]
Agree to Bryn's point, that method could be refactored. A new Jira ticket could be created for refactoring the method.

**Comment by Trimikraj** [comment]
Refactoring ticket has been added: https://gada.atlassian.net/browse/PIM-422

**Pull request merged**
